# # name = "abhinash "
# # age = 20
# # marks= 100
# # print(name)
# # print(age)
# # print(marks)
# # print()




# # name = "A"
# # Name = "B"
# # naMe = "D"
# # n_a_m_e = "E"
# # _name = "f"
# # name_ = "G"
# # _name_ = "H"
# # na56me = "I"
# # print(name,Name,naMe, n_a_m_e )


# #y = "abhinash"
# #print("hi"in y)
# #print('ha'in{}"?;p-o0,9n8by7tv6rc5ex4



# # data = {101:"Raj" , 102: "Raman", 103 : "sunil"} 
# # print (type(data))
# # print (type[102])


# #print(type(true))
# # a=[10,20,30,40,50 , 'programming']
# # print (a)
# # print (type(a))




# # rg = range (20, 10 ,-2)
# # print (rg[4])
# # print(type(rg))


# # for i in range (10):
# #     if(i==5):
# #        continue
# #     print(i)
# # print("rest of the code")


# # i = 1
# # while i<= 20:
# #     print(2,'*',i, "=" ,i*2 )
# #     i = i+1
    
# # a = [1,2,3,4]
# # sum = 0
# # i = 0
# # list = len(a)
# # while i < list:
# #     sum = sum+a[i]
# #     i = i +1
# # print(sum)


# # a = [1,2,3,4]
# # sum = 0
# # i = 0
# # list = len(a)
# # while i < list:
# #     sum = sum+a[0]
# #     i = i +1
# # print(sum)


# # a= [1,2,3,4]
# # b= []
# # c = len(a)-1
# # while c >= 0:
# #     num = a[c]
# #     b.append(num)
# #     c= c-1
# # print(b)

# # a= "krishna"
# # i= 0
# # b =""
# # c = len(a)-1
# # while i<=c:
# #     b= a[i]+b
# #     i+=1
# # print(b)


# # while True:
# #    userInp = input('Enter a vowel letter: ')
# #    vowels = ['a','e','i','o','u']
# #    if userInp in vowels:
# #       print('It\'s a vowel')
# #       break
# #    else:
# #       print('Please try again')
# #       pass
   
# # i = 0
# # vowels = ['a','e','i','o','u']

# # while (i == 0):
# #    x = input('Enter a vowel letter please: ')
# #    if x in vowels:
# #       print('It is a vowel')
# #       i+=1   
# #    else:
# #       print('It is not a vowel, please try again')


# a =1 
# while a<=5:
#     print(a)
#     a+=1
# else:
#     print("while condition false so else part execyred")
# print("rest")





# a=1
# while True:
#     print(a)

# i = 0
# while True:
#     i+=1
#     print(i)
#     if(i==3):
#         break
# print("rest of the code")

# i = 1
# while i<= 3:
#     print("outer loop" , i)
#     i = i+1
#     j=1
#     while j<=5:
#         print('inner loop',j)
#         j+=1
# print('rest of the code')



# i = 1
# while i<= 10:
#     if i ==5:
#         break
#     print(i)
#     i = i+1


# i = 1
# while i<= 10:
#     i = i+1
#     if i ==5:
#         continue
#     print(i)
    